# Generated by Django 4.2.6 on 2023-10-29 08:51

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Questionare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Survey Name", models.CharField(max_length=100)),
                (
                    "Survey's Activity Status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("suspend", "Suspended"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=10,
                    ),
                ),
                (
                    "Date start",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_index=True,
                        help_text="Date, where the survey will be started",
                    ),
                ),
                (
                    "Date finish",
                    models.DateTimeField(
                        db_index=True,
                        help_text="Date, where the survey will be finished",
                    ),
                ),
                ("Allow Annonimouse", models.BooleanField(default=True)),
            ],
        ),
    ]
