# Generated by Django 4.2.6 on 2023-10-29 10:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionare",
            name="Date finish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 30, 10, 27, 27, 824174, tzinfo=datetime.timezone.utc
                ),
                help_text="Date, where the survey will be finished",
            ),
        ),
        migrations.AlterField(
            model_name="questionare",
            name="Date start",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(
                    2023, 10, 29, 10, 27, 27, 824155, tzinfo=datetime.timezone.utc
                ),
                help_text="Date, where the survey will be started",
            ),
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Question", models.TextField(verbose_name="Questions")),
                (
                    "Allow Multiple",
                    models.BooleanField(
                        default=False, help_text="Is more than one answer allowed"
                    ),
                ),
                (
                    "questionare",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey.questionare",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Answer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Question", models.TextField(verbose_name="Questions")),
                (
                    "Correct?",
                    models.BooleanField(
                        default=False, help_text="Is the answer is correct"
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="survey.question",
                    ),
                ),
            ],
        ),
    ]
