# Generated by Django 4.2.6 on 2023-10-29 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("survey", "0002_alter_questionare_date_finish_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="questionare",
            name="Date finish",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 10, 30, 10, 49, 23, 756770, tzinfo=datetime.timezone.utc
                ),
                help_text="Date, where the survey will be finished",
            ),
        ),
        migrations.AlterField(
            model_name="questionare",
            name="Date start",
            field=models.DateTimeField(
                db_index=True,
                default=datetime.datetime(
                    2023, 10, 29, 10, 49, 23, 756750, tzinfo=datetime.timezone.utc
                ),
                help_text="Date, where the survey will be started",
            ),
        ),
    ]
