# Generated by Django 4.2.6 on 2023-10-30 15:25

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_alter_questionare_date_finish_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionare',
            options={'ordering': ('-date_from', 'activity_status')},
        ),
        migrations.RemoveField(
            model_name='questionare',
            name='Allow Annonimouse',
        ),
        migrations.RemoveField(
            model_name='questionare',
            name='Date finish',
        ),
        migrations.RemoveField(
            model_name='questionare',
            name='Date start',
        ),
        migrations.RemoveField(
            model_name='questionare',
            name='Survey Name',
        ),
        migrations.RemoveField(
            model_name='questionare',
            name="Survey's Activity Status",
        ),
        migrations.AddField(
            model_name='questionare',
            name='activity_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspend', 'Suspended')], db_index=True, default='draft', max_length=10, verbose_name="Survey's Activity Status"),
        ),
        migrations.AddField(
            model_name='questionare',
            name='date_from',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Date, where the survey will be started', verbose_name='Date start'),
        ),
        migrations.AddField(
            model_name='questionare',
            name='date_upto',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 31, 15, 25, 30, 673368, tzinfo=datetime.timezone.utc), help_text='Date, where the survey will be finished', verbose_name='Date finish'),
        ),
        migrations.AddField(
            model_name='questionare',
            name='is_anonymous',
            field=models.BooleanField(default=True, verbose_name='Allow Annonimouse'),
        ),
        migrations.AddField(
            model_name='questionare',
            name='title',
            field=models.CharField(default='New survey', max_length=100, verbose_name='Survey Name'),
        ),
    ]
