# Generated by Django 4.2.6 on 2023-11-02 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0007_remove_answer_correct__remove_answer_question_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionare',
            name='date_from',
            field=models.DateField(db_index=True, default=datetime.date(2023, 11, 2), help_text='Date, where the survey will be started', verbose_name='Date start'),
        ),
        migrations.AlterField(
            model_name='questionare',
            name='date_upto',
            field=models.DateField(default=datetime.date(2023, 11, 3), help_text='Date, where the survey will be finished', verbose_name='Date finish'),
        ),
    ]
