# Generated by Django 4.2.6 on 2023-11-03 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0009_alter_questionare_date_from_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='text',
        ),
    ]
