# Generated by Django 4.2.6 on 2023-11-05 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0012_alter_questionare_date_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionare',
            name='must_answers',
            field=models.BooleanField(default=True, verbose_name='Is all answers mandatory'),
        ),
        migrations.AlterField(
            model_name='questionare',
            name='is_anonymous',
            field=models.BooleanField(default=True, verbose_name='Allow Anonymous'),
        ),
    ]
