# Generated by Django 4.2.6 on 2023-11-16 08:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0018_alter_questionare_date_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionare',
            name='date_from',
            field=models.DateField(db_index=True, default=datetime.date(2023, 11, 16), help_text='Date, where the survey will be started', verbose_name='Date start'),
        ),
        migrations.AlterField(
            model_name='questionare',
            name='date_upto',
            field=models.DateField(default=datetime.date(2023, 11, 17), help_text='Date, where the survey will be finished', verbose_name='Date finish'),
        ),
    ]
