# Generated by Django 4.2.6 on 2023-11-07 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0015_alter_questionare_date_from_and_more'),
        ('accounts', '0002_rename_userprofiles_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=100)),
                ('responses', models.ManyToManyField(to='survey.response')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.surveyuser')),
            ],
        ),
    ]
