# Generated by Django 4.2.6 on 2023-11-09 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_surveyuser_options_alter_surveyuser_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyuser',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='surveyuser',
            name='last_login',
            field=models.DateTimeField(null=True),
        ),
    ]
