# Generated by Django 4.2.6 on 2023-11-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0005_alter_surveyuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveyuser',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='surveyuser_set', related_query_name='surveyuser', to='auth.group', verbose_name='groups'),
        ),
    ]
