# Generated by Django 4.2.6 on 2023-11-13 15:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_surveysession_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveysession',
            name='date_survey',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
